package model;
// Generated May 15, 2018 8:48:12 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;




/**
 * Studentdetail generated by hbm2java
 */
public class Studentdetail  implements Serializable {

    
     private String userId;
     private String firstName;
     private String lastName;
     private String gender;
     private Date dob;
     private String address;
     private String phone;
     private String email;
     private String password;

    public Studentdetail() {
    }

	
    public Studentdetail(String userid) {
        this.userId = userid;
    }

    public Studentdetail(String userId, String firstName, String lastName, String gender, Date dob, String address, String phone, String email, String password) {
        this.userId = userId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.dob = dob;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.password = password;
    }
    
   
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return "Studentdetail{" + "userid=" + userId + ", firstname=" + firstName + ", lastname=" + lastName + ", gender=" + gender + ", dob=" + dob + ", address=" + address + ", phone=" + phone + ", email=" + email + ", password=" + password + '}';
    }




}


